// templates/vue-green/client/js/components/Hello.vue
<template>
<h1>Hello from {{ compiler }} and {{ framework }}!</h1>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';

@Component({
    props: ['framework', 'compiler']
})
export default class Hello extends Vue {
    framework: string;
    compiler: string;
}
</script>

// templates/react/client/js/components/Hello.tsx
import React from 'react';

interface HelloProps {
    compiler: string;
    framework: string;
}

// State is never set so we use the `undefined` type.
export class Hello extends React.Component<HelloProps, undefined> {
    render() {
        return <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>;
    }
}
