// templates/vue/client/js/components/Hello.vue
<template>
    <h1>Hello from {{ compiler }} and {{ framework }}!</h1>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';

@Component({
    props: ['framework', 'compiler']
})
export default class Hello extends Vue {
    framework = '';
    compiler = '';
}
</script>

// templates/preact/client/js/components/Hello.tsx
import { h, Component, JSX } from 'preact';

interface HelloProps {
    compiler: string;
    framework: string;
}

export class Hello extends Component<HelloProps, undefined> {
    render(): h.JSX.Element {
        return <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>
    }
}
