// templates/mithril/client/js/components/Hello.tsx
import m, { Component } from 'mithril';

interface HelloProps {
    compiler: string;
    framework: string;
}

export class Hello implements Component<HelloProps, undefined> {
    view(vnode: m.Vnode<HelloProps, undefined>) {
        return <h1>Hello from {vnode.attrs.compiler} and {vnode.attrs.framework}!</h1>
    }
}

// templates/vue-green/client/js/components/Hello.vue
<template>
<h1>Hello from {{ compiler }} and {{ framework }}!</h1>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';

@Component({
    props: ['framework', 'compiler']
})
export default class Hello extends Vue {
    framework: string;
    compiler: string;
}
</script>
